---
Butler:
  slackConfig:
    webhookURL: https://hooks.slack.com/services/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
    loginNotificationChannel: sense-user-activity
    taskFailureChannel: sense-task-failure
  mqttConfig:
    brokerIP: mqtt.ptarmiganlabs.net
    taskFailureTopic: qliksense/task_failure
    taskFailureServerStatusTopic: qliksense/butler/task_failure_server
    sessionStartTopic: qliksense/session/start
    sessionStopTopic: qliksense/session/stop
    connectionOpenTopic: qliksense/connection/open
    connectionCloseTopic: qliksense/connection/close
    sessionServerStatusTopic: qliksense/butler/session_server
    activeUserCountTopic: qliksense/users/active/count
    activeUsersTopic: qliksense/users/active/usernames
  udpServerConfig:
    serverIP: 10.132.0.2
    portSessionConnectionEvents: 9997
    portTaskFailure: 9998
  restServerConfig:
    serverPort: 8080
  configEngine:
    server: sense.ptarmiganlabs.net
    serverPort: '4747'
    isSecure: 'true'
    headers:
      X-Qlik-User: UserDirectory=Internal;UserId=sa_repository
    cert: C:\secret\sense_cert\client.pem
    key: C:\secret\sense_cert\client_key.pem
    rejectUnauthorized: 'false'
  configQRS:
    authentication: certificates
    host: sense.ptarmiganlabs.net
    useSSL: true
    port: 4242
    headerKey: X-Qlik-User
    headerValue: UserDirectory=Internal; UserId=sa_repository
    cert: C:\secret\sense_cert\client.pem
    key: C:\secret\sense_cert\client_key.pem
    ca: C:\secret\sense_cert\root.pem
  qvdPath: C:\sense_data\prod\qvd
  gitHub:
    host: api.github.com
    pathPrefix: ''
